### ISSUE TITLE
1.13.2 data

### ISSUE THREAD

**Issue by uncovery** [rom1504/minecraft-assets#2]
Could you kindly update with 1.13.2 data? Thanks!

**Comment by rom1504** [comment]
sure, will do

how do you use the data ?

**Comment by uncovery** [comment]
I am using it to display graphics on the website of my mincraft server. We are running an e-commerce like system that is accessible through the website.

**Comment by rom1504** [comment]
done
demo at http://minecraft-data.prismarine.js.org/

**Comment by uncovery** [comment]
Thanks a lot!
